name: Exemplo de fluxo para código"

on:
  push:
    branches: [ develop, main]
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 24.19.0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_MODE: test
    steps:
      - name: "Obter código"
        uses: actions/checkout@v4
      
      - name: "Instalar dependências"
        run: |
          echo "Instalando dependências com Node.js ${{ env.NODE_VERSION }}"
          npm ci

      - name: Executar testes
        run: |
          echo "Executando testes com Node.js ${{ env.NODE_VERSION }}"
          npm test

      - name: Condicional
        if: github.event_name == 'pull_request'
        run: echo "Rodando um PR"
