name: "Exemplo com Environments do GitHub"

on:
  workflow_dispatch:

env:
  APP_NAME: demo-app            # escopo do workflow
  LOG_LEVEL: info

jobs:
  demonstrar-environments:
    name: "Demonstrar uso de Environments"
    runs-on: ubuntu-latest
    environment: production # ativa vars e secrets do ambiente "production" informado no repositório do GitHub
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }} # usa vars do ambiente/repo/org conforme o environment

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v4

      - name: "Mostrar Environments disponíveis"
        run: |
          echo "====== VARIAVEIS DO ENVIRONMENT ======"
          echo "Este é o ambiente de ${ENVIRONMENT}. "
          echo "DEBUG_MODE: ${{ vars.DEBUG_MODE }}"

      - name: Mapear segredo para o shell
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          echo "Demonstra uso de secret mascarada: DB_PASS=${DB_PASS}"

      - name: "Condicional usando vars somente em production"
        if: ${{ vars.ENVIRONMENT == 'production' }}
        run: |
          echo "====== CONDICIONAL PARA PRODUCTION ======"
          echo "Este passo só será executado se o Environment for 'production'."
