name: Hello Github Actions

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/hello-world.yml' # Quando houver alguma ação neste arquivo ele irá executar este workflow. Comentar para executar sempre que houver push na branch main
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/hello-world.yml' # Quando houver alguma ação neste arquivo ele irá executar este workflow. Comentar para executar sempre que houver pull request na branch main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello GitHub Actions"

      - name: Mostrar informações do sistema
        run: |
          echo "Sistema Operacional: ${{ runner.os }}"
          echo "Diretório Atual: $(pwd)"
          echo "Data e Hora: $(date)"
          echo "Usuário: $(whoami)"

      - name: Listar arquivos do repositório
        run: ls -la

      - name: Comandos múltiplos
        run: |
          echo "Este é o Lab 01 de testes com github actions"
          echo "Workflow executado com sucesso!"
          echo "Pronto para o próximo passo!"
